name: mdse
channels:
  - pytorch
  - soumith
  - defaults
  - conda-forge
dependencies:
  - blas=1.0=mkl
  - brotli=1.0.9=h8ffe710_7
  - brotli-bin=1.0.9=h8ffe710_7
  - ca-certificates=2022.12.7=h5b45459_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cudatoolkit=11.0.221=h74a9793_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - flit-core=3.6.0=pyhd3eb1b0_0
  - fonttools=4.25.0=pyhd3eb1b0_0
  - freetype=2.12.1=ha860e81_0
  - icu=68.2=h0e60522_0
  - intel-openmp=2021.4.0=haa95532_3556
  - joblib=1.2.0=pyhd8ed1ab_0
  - jpeg=9e=h2bbff1b_0
  - kiwisolver=1.4.2=py37hd77b12b_0
  - lerc=3.0=hd77b12b_0
  - libblas=3.9.0=1_h8933c1f_netlib
  - libbrotlicommon=1.0.9=h8ffe710_7
  - libbrotlidec=1.0.9=h8ffe710_7
  - libbrotlienc=1.0.9=h8ffe710_7
  - libcblas=3.9.0=5_hd5c7e75_netlib
  - libclang=11.1.0=default_h5c34c98_1
  - libdeflate=1.8=h2bbff1b_5
  - liblapack=3.9.0=5_hd5c7e75_netlib
  - libpng=1.6.37=h2a8f88b_0
  - libtiff=4.4.0=h8a3f274_2
  - libuv=1.40.0=he774522_0
  - libwebp=1.2.4=h2bbff1b_0
  - libwebp-base=1.2.4=h2bbff1b_0
  - lz4-c=1.9.3=h2bbff1b_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib=3.5.3=py37h03978a9_2
  - matplotlib-base=3.5.3=py37hbaab90a_2
  - mkl=2021.4.0=haa95532_640
  - mkl-service=2.4.0=py37h2bbff1b_0
  - mkl_fft=1.3.1=py37h277e83a_0
  - mkl_random=1.2.2=py37hf11a4ad_0
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ninja=1.10.2=haa95532_5
  - ninja-base=1.10.2=h6d14046_5
  - numpy=1.21.5=py37h7a0a035_3
  - numpy-base=1.21.5=py37hca35cd5_3
  - openssl=1.1.1s=h2bbff1b_0
  - packaging=22.0=pyhd8ed1ab_0
  - pillow=9.2.0=py37hdc2b20a_1
  - pip=22.3.1=py37haa95532_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pyqt=5.12.3=py37h1834ac0_4
  - python=3.7.15=h6244533_1
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.7=2_cp37m
  - pytorch=1.7.0=py3.7_cuda110_cudnn8_0
  - qt=5.12.9=h5909a2a_4
  - scikit-learn=0.22.1=py37h7208079_1
  - scipy=1.7.3=py37hb6553fb_0
  - setuptools=65.5.0=py37haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.40.0=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - torchvision=0.8.0=py37_cu110
  - tornado=6.2=py37hcc03f2d_0
  - typing_extensions=4.4.0=py37haa95532_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.37.1=pyhd3eb1b0_0
  - wincertstore=0.2=py37haa95532_2
  - xz=5.2.8=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - zstd=1.5.2=h19a0ad4_0
  - pip:
      - pyqt5-sip==4.19.18
      - pyqtchart==5.12
      - pyqtwebengine==5.12.1

